package cuong.data.javasample;
// Generated Aug 2, 2016 10:52:30 AM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetail generated by hbm2java
 */
@Entity
@Table(name = "orderdetail", catalog = "classicmodels")
public class Orderdetail implements java.io.Serializable {

    private OrderdetailId id;
    private Order order;
    private Product product;
    private int quantityOrdered;
    private BigDecimal priceEach;
    private short orderLineNumber;

    public Orderdetail() {
    }

    public Orderdetail(OrderdetailId id, Order order, Product product, int quantityOrdered, BigDecimal priceEach,
            short orderLineNumber) {
        this.id = id;
        this.order = order;
        this.product = product;
        this.quantityOrdered = quantityOrdered;
        this.priceEach = priceEach;
        this.orderLineNumber = orderLineNumber;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "orderNumber", column = @Column(name = "orderNumber", nullable = false)),
            @AttributeOverride(name = "productCode", column = @Column(name = "productCode", nullable = false, length = 15)) })
    public OrderdetailId getId() {
        return this.id;
    }

    public void setId(OrderdetailId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orderNumber", nullable = false, insertable = false, updatable = false)
    public Order getOrder() {
        return this.order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "productCode", nullable = false, insertable = false, updatable = false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @Column(name = "quantityOrdered", nullable = false)
    public int getQuantityOrdered() {
        return this.quantityOrdered;
    }

    public void setQuantityOrdered(int quantityOrdered) {
        this.quantityOrdered = quantityOrdered;
    }

    @Column(name = "priceEach", nullable = false, precision = 10)
    public BigDecimal getPriceEach() {
        return this.priceEach;
    }

    public void setPriceEach(BigDecimal priceEach) {
        this.priceEach = priceEach;
    }

    @Column(name = "orderLineNumber", nullable = false)
    public short getOrderLineNumber() {
        return this.orderLineNumber;
    }

    public void setOrderLineNumber(short orderLineNumber) {
        this.orderLineNumber = orderLineNumber;
    }

}
