package cuong.data.javasample;
// Generated Aug 2, 2016 10:52:30 AM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productline generated by hbm2java
 */
@Entity
@Table(name = "productline", catalog = "classicmodels")
public class Productline implements java.io.Serializable {

    private String productLine;
    private String textDescription;
    private String htmlDescription;
    private byte[] image;
    private Set<Product> products = new HashSet<Product>(0);

    public Productline() {
    }

    public Productline(String productLine) {
        this.productLine = productLine;
    }

    public Productline(String productLine, String textDescription, String htmlDescription, byte[] image,
            Set<Product> products) {
        this.productLine = productLine;
        this.textDescription = textDescription;
        this.htmlDescription = htmlDescription;
        this.image = image;
        this.products = products;
    }

    @Id

    @Column(name = "productLine", unique = true, nullable = false, length = 50)
    public String getProductLine() {
        return this.productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine;
    }

    @Column(name = "textDescription", length = 4000)
    public String getTextDescription() {
        return this.textDescription;
    }

    public void setTextDescription(String textDescription) {
        this.textDescription = textDescription;
    }

    @Column(name = "htmlDescription", length = 16777215)
    public String getHtmlDescription() {
        return this.htmlDescription;
    }

    public void setHtmlDescription(String htmlDescription) {
        this.htmlDescription = htmlDescription;
    }

    @Column(name = "image")
    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productline")
    public Set<Product> getProducts() {
        return this.products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }

}
